name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        rsync -avz --exclude='.git*' -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:/var/www/html/

    - name: SSH into EC2 and run deployment script
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
          cd /var/www/html
          # Here you can add any commands to set up your environment, for example:
          composer install
          php artisan migrate --force
          # Restart services if necessary
          sudo systemctl restart apache2
        EOF
