name: Deploy PHP to EC2

on:
  push:
    branches:
      - master  # Change to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.0

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.PEM_FILE }}

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: SSH into EC2 and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@172-31-47-138 << 'EOF'
          cd /var/www/html/learning-php
          git pull origin main
        EOF
